name: Weekly Odoo Check

on:
  schedule:
    - cron: '0 9 * * 1' # lunes 9am
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      ODOO_LOOPITA_EMAIL: ${{ secrets.ODOO_LOOPITA_EMAIL }}
      ODOO_LOOPITA_PASSWORD: ${{ secrets.ODOO_LOOPITA_PASSWORD }}
      ODOO_CAROLINAGUTT_EMAIL: ${{ secrets.ODOO_CAROLINAGUTT_EMAIL }}
      ODOO_CAROLINAGUTT_PASSWORD: ${{ secrets.ODOO_CAROLINAGUTT_PASSWORD }}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
      GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install deps
        run: |
          npm install
          ls -la node_modules/.bin
          chmod +x node_modules/.bin/playwright
          chmod +x node_modules/.bin/playwright-core || true
          npx playwright --version
          npx playwright install --with-deps

      - name: Run script
        run: node test.js
